version: '3'

services:
  mysql:
    container_name: mysql-3306
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"

    ports:
      - "3306:3306"
    volumes:
      - "./db:/var/lib/mysql"
      - "./conf/my.cnf:/etc/my.cnf"
      - "./init:/docker-entrypoint-initdb.d/"


  delay-server:
    container_name: my-blog
    build: .
    image: my-blog-master
    ports:
      - "8080:8080"
    volumes:
      - "./tmp-log:/tmp"
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      QINIU_ACCESSKEY: ""
      QINIU_SERECTKEY: ""
      QINIU_BUCKET: ""
      QINIU_CDN_URL: ""
